name: Install SCP

on:
  workflow_dispatch:
  #push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SCP
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client
          echo $(which scp)

