name: Build and Deploy Frontend to DockerHub

on:
  workflow_dispatch:
  #push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kubectl
        run: kubectl version
        
      - name: AWS
        run: aws --version
